# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c1e7e30230f268cc5caf5024507b213f18c11b14f14b52f4b5854f6abb9e098fd912a9a85b7b46eef0afd7586c7b1fb69047e0416a457e91b990265868e93a6

test:
  secret_key_base: feaefa77240f1cdc59a6db9d3daeeb66252611f6a48c462e90b9e01700cd42e5bc76079ddbeac78ec328e902ef2fd8cb7a0e28a14489ec10467fedb41ed4de73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
